autoload:
  sfAzureSDKPlugin_lib:
    name:           azure plugin lib
    path:           <?php echo realpath(dirname(__FILE__).'/../lib')."\n" ?>
    recursive:      true
    exclude:        [vendor]
#  sfAzureSDKAutoloader:
#    name:           azure sdk autoloader
#    files:
#      WindowsAzureLoader : <?php echo realpath(dirname(__FILE__).'/../lib/vendor/azure-sdk-for-php/WindowsAzure/WindowsAzure.php')."\n"; ?>
#  