autoload:
  sfAzureSDKPlugin_lib:
    name:           azure plugin lib
    path:           <?php echo realpath(dirname(__FILE__).'/../lib')."\n" ?>
    recursive:      true
    exclude:        [vendor]
