#config/account.yml:
#  class:    sfAzureAccountConfigInstanceHandler
#  file: %SF_PLUGINS_DIR%/sfAzureSDKPlugin/lib/config/sfAzureAccountConfigInstanceHandler.class.php
#config/autoload.yml:
#  class:    sfAutoloadConfigHandler  